### ISSUE TITLE
File path not found when using rector

### ISSUE THREAD

**Issue by divyesh19** [palantirnet/drupal-rector#131]
Hi,

I am facing an issue when trying to run rector on my code, it is not able to process the file with below error:
`Could not process ... file, due to: File path phar: /vendor/rector/rector-prefixed/rector/packages/node-type-resolver/src/TypeAnalyzer/ArrayTypeAnalyzer.php was not found while creating "_HumbugBox3630ef99eac4\Symplify\SmartFileSystem\SmartFileInfo" object.`

It updates the code though, removing namespaces, similar to what mattpaz mentioned here #120 
Could this be related to [rector-prefixed](https://github.com/rectorphp/rector-prefixed/tree/v0.7.9) 0.7.9, since the file mentioned in this error (ArrayTypeAnalyzer.php) is not present in rector-prefixed 0.7.9 but is present in [0.9.5](https://github.com/rectorphp/rector-prefixed/tree/0.9.5).

Using below versions:
palantirnet/drupal-rector: 0.5.6
phpstan/phpstan: 0.12.64
mglaman/drupal-check: 1.1.6

**Comment by damontgomery** [comment]
Sorry that you're having these issues and thanks for looking into the issue.

I'm not sure that we need to update to fix your issue, but if we do, we probably need to revisit the core update first. See #122. Since this is a sizable change I don't have a good estimate as to when we'll be able to move forward with that.

If you are looking for a short term fix, you might be able to create a simple D8 site using a process here for reference: https://github.com/palantirnet/drupal-rector/blob/master/.github/workflows/local_package_run_rector.yml. And then drop in your modules that you want to update.

**Comment by divyesh19** [comment]
Thanks for the quick revert. I'll try what you have suggested for now.
