### ISSUE TITLE
PHP Fatal error:  Declaration of Drupal\Tests\BrowserTestBase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void

### ISSUE THREAD

**Issue by MegaChriz** [palantirnet/drupal-rector#59]
When I run a command like the following:
`vendor/bin/rector process web/modules/contrib/feeds --dry-run`

I get this error:
`PHP Fatal error:  Declaration of Drupal\Tests\BrowserTestBase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /Users/youri/Websites/drupal/drupalsites/drupal9/web/core/tests/Drupal/Tests/BrowserTestBase.php on line 388
Fatal error: Declaration of Drupal\Tests\BrowserTestBase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /Users/youri/Websites/drupal/drupalsites/drupal9/web/core/tests/Drupal/Tests/BrowserTestBase.php on line 388`

I tried this on a fresh Drupal 9 install, with the latest 9.0.x-dev of Drupal 9, using the composer template `drupal/recommended-project`.

Here is my composer.json:
```JSON
{
    "name": "drupal/recommended-project",
    "description": "Project template for Drupal 8 projects with a relocated document root",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "homepage": "https://www.drupal.org/project/drupal",
    "support": {
        "docs": "https://www.drupal.org/docs/user_guide/en/index.html",
        "chat": "https://www.drupal.org/node/314178"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "composer/installers": "^1.2",
        "drupal/admin_toolbar": "^2.2",
        "drupal/core": "~9.0.0",
        "drupal/core-composer-scaffold": "^9",
        "drupal/core-project-message": "^9",
        "drupal/core-recommended": "^9",
        "drush/drush": "^10.2"
    },
    "require-dev": {
        "behat/mink": "^1.8",
        "behat/mink-goutte-driver": "^1.2",
        "behat/mink-selenium2-driver": "^1.4",
        "composer/composer": "^1.9.1",
        "drupal/coder": "^8.3.7",
        "easyrdf/easyrdf": "^0.9",
        "justinrainbow/json-schema": "^5.2",
        "mikey179/vfsstream": "^1.6.8",
        "palantirnet/drupal-rector": "^0.5.0",
        "phpspec/prophecy": "^1.7",
        "phpunit/phpunit": "^8.4.1",
        "symfony/browser-kit": "^4.4",
        "symfony/css-selector": "^4.4",
        "symfony/dom-crawler": "^4.4 !=4.4.5",
        "symfony/error-handler": "^4.4",
        "symfony/filesystem": "^4.4",
        "symfony/finder": "^4.4",
        "symfony/lock": "^4.4",
        "symfony/phpunit-bridge": "^4.4"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    },
    "extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "web/"
            }
        },
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/Commands/contrib/{$name}": ["type:drupal-drush"],
            "web/modules/custom/{$name}": ["type:drupal-custom-module"],
            "web/themes/custom/{$name}": ["type:drupal-custom-theme"]
        },
        "drupal-core-project-message": {
            "include-keys": ["homepage", "support"],
            "post-create-project-cmd-message": [
                "<bg=blue;fg=white>                                                         </>",
                "<bg=blue;fg=white>  Congratulations, you’ve installed the Drupal codebase  </>",
                "<bg=blue;fg=white>  from the drupal/recommended-project template!          </>",
                "<bg=blue;fg=white>                                                         </>",
                "",
                "<bg=yellow;fg=black>Next steps</>:",

                "  * Install the site: https://www.drupal.org/docs/8/install",
                "  * Read the user guide: https://www.drupal.org/docs/user_guide/en/index.html",
                "  * Get support: https://www.drupal.org/support",
                "  * Get involved with the Drupal community:",
                "      https://www.drupal.org/getting-involved",
                "  * Remove the plugin that prints this message:",
                "      composer remove drupal/core-project-message"
            ]
        }
    }
}
```

I also have a rector.yml in the root directory that was created after running `cp vendor/palantirnet/drupal-rector/rector-config-web-dir.yml rector.yml`.

I did found the following Drupal core issue:
https://www.drupal.org/project/drupal/issues/3114041

And I saw a file called TestCase.php in web/sites/simpletest. In there, the `setUp()` method doesn't have `:void` as return type:
```php
/**
 * This method is called before each test.
 */
protected function setUp()
{
}
```

So at first glance, it looks like we should somehow instruct Rector to load "web/sites/simpletest/TestCase.php", but I'm not sure how.

I temporary fixed the issue by copying "web/sites/simpletest/TestCase.php" to "vendor/phpunit/phpunit/src/Framework/TestCase.php".

**Comment by damontgomery** [comment]
@MegaChriz, thanks for looking at this. I haven't tested Rector with Drupal 9, but that seems like something that would be helpful.

The issues you are encountering seem like autoloading issues that are related to Rector in that Rector is trying to load the classes you've mentioned.

The issue you link to seems to indicate that Drupal 9 has issues with that version of PhpUnit. Rector is complaining, because it's trying to load the base class from core (which extends a class from PhpUnit) and it can't do that, so it fails.

I think your TestCase.php might be something separate, but I'm not super familiar with PhpUnit tests in Drupal and have very little experience with simpletest in Drupal. Does it create the `web/sites/simpletest` folder?

Rector is not aware of classes in that folder. We did have to point it to the folders where classes would typically be, but this assumes they aren't in other places as well. :(

In the `rector.yml`, there is a list of paths to search for classes,

```
parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'
```

The `sites/` is not listed there, so it wouldn't find the class.

Maybe that would resolve your issue?

Summary:
- Try to resolve the issue between Drupal 9 and PhpUnit if you haven't already
- Try to run Rector on a file that doesn't depend on PhpUnit and see if that works
- If you are still having issues, maybe you can add autoload paths to `rector.yml`

We have a few automated tests running on our code and maybe we can run a version with Drupal 9 to catch these issues.

**Comment by damontgomery** [comment]
#117 adds support for Drupal 9. We're reviewing that now. When that is added, you can run Drupal 9 rules only on Drupal 9. I think the recommendation in general will be to run the rules for the version you have installed.

The drupal.org page recommends fixing deprecations before upgrading. https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-to-drupal-9-or-higher. I think this will be a requirement, because if the stuff is gone in the newer version, the auto-loading can break easily.

I'll try to update documentation around this. It makes sense people might want to do it the other way, so we should provide guidance.

Thanks again.

**Comment by agentrickard** [comment]
https://www.drupal.org/project/rector/issues/3219156 is the proper place to track the Drupal 9 compatibility issue.
